version: '3.0'
services:
  # backend-app:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   image: api:latest
  #   container_name: api
  #   volumes:
  #     - ./:/app
  #   ports:
  #     - ${APP_PORT}:${APP_PORT}
  #   depends_on:
  #     - db
  #     - cache
  #   restart: always
  db:
    container_name: '${MYSQL_HOST}'
    image: mysql:8.0
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: '${MYSQL_DATABASE_NAME}'
      MYSQL_ROOT: '${MYSQL_USERNAME}'
      MYSQL_ROOT_PASSWORD: '${MYSQL_PASSWORD}'
    ports:
      - '${MYSQL_PORT}:${MYSQL_PORT}'
    expose: 
      - '${MYSQL_PORT}'
    volumes:
      - ./data/mysql:/var/lib/mysql

  cache:
    container_name: ${REDIS_HOST}
    image: redis:6.2-alpine
    restart: always
    ports:
      - "${REDIS_PORT}:6379"
    command: redis-server --save 60 1 --loglevel warning --requirepass ${REDIS_PASSWORD}
    volumes:
      - ./data/cache:/data

volumes:
  db:
  cache: