version: '3.0'
services:
  db:
    container_name: '${MYSQL_HOST}'
    image: mysql:8.0
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: '${MYSQL_DATABASE_NAME}'
      MYSQL_ROOT: '${MYSQL_USERNAME}'
      MYSQL_ROOT_PASSWORD: '${MYSQL_PASSWORD}'
    ports:
      - '${MYSQL_PORT}:${MYSQL_PORT}'
    expose: 
      - '${MYSQL_PORT}'
    volumes:
      - ./data/mysql:/var/lib/mysql